export const GAME_TYPES = {
    WWF: 1,
    SCA_US: 2,
    SCA_UK: 3,
    WORD_SCAPE: 4,
    ANAGRAM: 5,
    FOUR_PIC: 6,
    JUMBLE_SOLVER: 7,
    WORD_CONNECT: 8,
    WORD_COOKIE: 9,
    WORD_CHUMS: 10,
    TEXT_TWIST: 11,
    CODE_CROSS: 12,
    WORD_FEUD: 13,
    WORD_BRAIN: 14,
    WORD_STORY: 15,
    WORD_SWIPE: 16,
    WORD_WARS: 17,
  };